---
sidebar: sidebar 
permalink: docs/rn_whatsnew.html 
summary: 이 NetApp HCI 버전의 새로운 기능에 대해 알아보십시오. 
keywords: netapp, hci, element, new, whatsnew 
---
= NetApp HCI의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element


[role="lead"]
NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 NetApp HCI을 정기적으로 업데이트합니다. NetApp HCI 1.10에는 스토리지 클러스터의 Element 소프트웨어 12.5가 포함되어 있습니다.

* 를 클릭합니다 <<NetApp HCI 1.10>> NetApp HCI 버전 1.10의 새로운 기능 및 업데이트에 대해 설명합니다.
* 를 클릭합니다 <<Element software 12.5>> 섹션 에서는 Element 12.5의 새로운 기능 및 업데이트에 대해 설명합니다.




== NetApp HCI 1.10

NetApp HCI 1.10은 보안 및 안정성 향상을 포함하며 배포 후 확장 유연성을 높입니다.



=== 구축 후 확장 유연성

NetApp HCI 1.10은 컴퓨팅 노드의 기본 구축 VMK 및 vmnic 구성 설정을 충족하기 위한 요구 사항을 제거하여 NetApp HCI 컴퓨팅 리소스를 확장하는 유연성을 높입니다. NetApp HCI 1.10부터 컴퓨팅 리소스를 확장할 때 NetApp HCI는 컴퓨팅 노드의 일반 VMK 구성만 예상합니다. link:task_nde_supported_net_changes.html["자세한 정보"].



=== 스토리지 노드 펌웨어 업데이트

NetApp HCI 1.10에는 스토리지 노드의 펌웨어 업데이트가 포함되어 있습니다. link:rn_relatedrn.html#storage-firmware["자세한 정보"].



=== 컴퓨팅 노드 펌웨어 업데이트

NetApp HCI 1.10에는 컴퓨팅 노드의 펌웨어 업데이트가 포함되어 있습니다. link:rn_relatedrn.html#compute-firmware["자세한 정보"].



=== vCenter Server 4.9 가용성을 위한 NetApp Element 플러그인

vCenter Server 4.9용 NetApp Element 플러그인은 관리 노드 12.5 및 NetApp HCI 1.10 릴리즈 외부에서 사용할 수 있습니다. 플러그인을 업그레이드하려면 의 지침을 따릅니다 link:concept_hci_upgrade_overview.html["NetApp HCI 업그레이드"] 문서화:



=== NetApp 하이브리드 클라우드 제어의 개선 사항

NetApp 하이브리드 클라우드 제어는 버전 1.10에서 향상되었습니다. link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["자세한 정보"^].



=== 해결된 문제 및 알려진 문제

NetApp 버그 온라인 툴에는 NetApp HCI, Element 소프트웨어 및 기타 제품에서 해결된 알려진 문제가 포함되어 있습니다. 에서 키워드 또는 버전을 사용하여 이러한 문제를 찾아볼 수 있습니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/bugsonline-tab["NetApp 온라인 버그"^].



== Element 소프트웨어 12.5

Element 12.5에는 향상된 스토리지 노드 액세스, 향상된 맞춤형 보호 도메인 관리 효율성, 새롭게 개선된 클러스터 장애 및 이벤트, 향상된 클러스터 UI 기능, 향상된 보안 및 Ansible을 사용한 자동 업그레이드가 도입되었습니다.



=== 스토리지 노드 액세스 향상

Element 12.5는 서명된 SSH 인증서를 사용하여 개별 노드에 대한 원격 액세스를 향상시킵니다. 스토리지 노드에 대한 보안 원격 액세스를 제공하기 위해 스토리지 노드의 RTFI 중에 's freadonly'라는 새로운 제한된 권한의 로컬 사용자 계정이 생성됩니다. 'readonly' 계정을 사용하면 기본적인 유지 관리 또는 문제 해결을 위해 스토리지 노드 백엔드에 액세스할 수 있습니다. 이제 클러스터 관리자에 대한 'upportAdmin' 액세스 유형을 구성하여 NetApp에서 필요에 따라 클러스터에 액세스하도록 허용할 수 있습니다.



=== 향상된 맞춤형 보호 도메인 관리 기능

Element 12.5는 기존 사용자 지정 보호 도메인을 빠르고 쉽게 보고 새로운 사용자 지정 보호 도메인을 구성할 수 있는 새로운 사용자 인터페이스를 제공합니다.



=== 새롭게 향상된 클러스터 장애, 이벤트 및 알림

Element 12.5는 새로운 클러스터 오류 코드 "BmcSelfTestFailed" 및 "CpuThermalEventThreshold"를 도입하여 시스템 문제 해결을 향상시킵니다. Element 12.5에는 nodeOffline, volumeOffline, driveHealthFault, networkr 등의 기존 클러스터 이벤트 및 알림에 대한 견고성이 향상되었습니다. 그리고 'cSumEvent'가 있습니다.



=== Create Cluster UI에서 Software Encryption at Rest를 활성화합니다

클러스터 생성 UI에 새로운 확인란이 추가된 Element 12.5에서는 클러스터 생성 시 SolidFire All-Flash 스토리지 클러스터에 클러스터 전체 소프트웨어 암호화를 사용하도록 설정할 수 있습니다.



=== 스토리지 노드 펌웨어 업데이트

Element 12.5에는 스토리지 노드의 펌웨어 업데이트가 포함됩니다. link:https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html#storage-firmware["자세한 정보"^].



=== 향상된 보안

Element 12.5에는 Apache log4j 취약점에 대한 Element 소프트웨어 노출을 종료하는 완화 요소가 포함되어 있습니다. VVOL(가상 볼륨) 기능을 활성화한 NetApp SolidFire 스토리지 클러스터는 Apache log4j 취약점에 노출됩니다. NetApp Element 소프트웨어의 Apache log4j 취약점에 대한 해결 방법에 대한 자세한 내용은 {url-peak} [KB 문서^]를 참조하십시오.

Element 11.x, 12.0 또는 12.2를 실행 중이거나 저장소 클러스터가 이미 Element 12.3 또는 12.3.1에 있고 VVol 기능이 활성화된 경우 12.5로 업그레이드하는 것이 좋습니다.

Element 12.5에는 120개 이상의 CVE 보안 취약점 해결도 포함되어 있습니다.



== Ansible을 사용하여 자동 업그레이드

Element 12.5를 사용하면 Ansible을 사용하여 전체 스토리지 클러스터의 롤링 업그레이드를 수행하여 Element 소프트웨어 업그레이드 워크플로우를 자동화할 수 있습니다. 시작하려면 로 이동합니다 https://github.com/NetApp-Automation["NetApp Ansible 리포지토리"^] GitHub에서 NAR_solidfire_sds_upgrade 역할 및 문서를 다운로드합니다.

[discrete]
== 자세한 내용을 확인하십시오

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["NetApp 하이브리드 클라우드 제어 및 관리 서비스 릴리즈 노트"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["NetApp HCI 및 NetApp Element 소프트웨어용 펌웨어 및 드라이버 버전"^]

