---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_management_node.html 
summary: NetApp HCI 시스템 업그레이드의 일부로 관리 노드를 업그레이드합니다. 
keywords: netapp, hci, on premise, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x, 12.5, 12.7 
---
= 관리 노드를 업그레이드합니다
:allow-uri-read: 


[role="lead"]
관리 노드를 버전 12.3.x 이상에서 관리 노드 12.5 이상으로 업그레이드할 수 있습니다.

스토리지 클러스터에서 Element 소프트웨어를 업그레이드하는 데 관리 노드 운영 체제를 더 이상 업그레이드할 필요가 없습니다. NetApp 하이브리드 클라우드 제어를 사용하여 관리 서비스를 최신 버전으로 간단히 업그레이드하여 Element 업그레이드를 수행할 수 있습니다. 보안 문제 해결과 같은 다른 이유로 관리 노드 운영 체제를 업그레이드하려면 시나리오에 따라 관리 노드 업그레이드 절차를 따르십시오.


NOTE: 관리 노드 12.2 이전 버전 업그레이드에 대한 정보가 필요한 경우 를 참조하십시오 https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_management_node.html["NetApp HCI 1.9 관리 노드 업그레이드 설명서"^].

다음 옵션 중 하나를 선택합니다.

*  a management node to version 12.5 or later from version 12.3.x or later
*  authentication using the management node REST API
+
관리 서비스 버전(1) 및 (2) 요소 스토리지 버전을 * 순차적으로 * 업데이트하고 * 기존 관리 노드를 * 유지하려면 이 옵션을 선택하십시오.




NOTE: 관리 서비스를 Element 스토리지 뒤에 순차적으로 업데이트하지 않으면 이 절차를 사용하여 재인증을 재구성할 수 없습니다. 대신 적절한 업그레이드 절차를 따르십시오.



== 관리 노드를 버전 12.3.x 이상에서 버전 12.5 이상으로 업그레이드합니다

새 관리 노드 가상 머신을 프로비저닝하지 않고도 관리 노드를 버전 12.3.x 이상에서 버전 12.5 이상으로 업그레이드할 수 있습니다.


NOTE: Element 12.5 이상의 관리 노드는 선택적 업그레이드입니다. 기존 배포에는 필요하지 않습니다.

.무엇을 &#8217;필요로 할거야
* 관리 노드 VM의 RAM은 24GB입니다.
* 업그레이드하려는 관리 노드는 버전 12.0이며 IPv4 네트워킹을 사용합니다. 관리 노드 버전 12.5 이상은 IPv6를 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다.

* NetApp 하이브리드 클라우드 제어를 사용하여 관리 서비스 번들을 최신 버전으로 업데이트했습니다. 다음 IP 주소로 NetApp 하이브리드 클라우드 제어에 액세스할 수 있습니다. '\https://<ManagementNodeIP>`
* 관리 노드를 버전 12.5 이상으로 업데이트하는 경우 계속하려면 관리 서비스 2.21.61 이상이 필요합니다.
* 에 대한 지침을 사용하여 추가 네트워크 어댑터를 구성했습니다(필요한 경우) link:task_mnode_install_add_storage_NIC.html["추가 스토리지 NIC 구성"].
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에는 추가 네트워크 어댑터가 필요할 수 있습니다. 영구 볼륨의 구성을 허용하도록 iSCSI 스토리지 네트워크에서 새 네트워크 어댑터를 구성합니다.

* 스토리지 노드가 Element 12.3.x 이상을 실행하고 있습니다.


.단계
. SSH 또는 콘솔 액세스를 사용하여 관리 노드 가상 머신에 로그인합니다.
. 를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["관리 노드 ISO"^] NetApp Support 사이트에서 관리 노드 가상 시스템까지 Element 소프트웨어의 경우.
+

NOTE: ISO의 이름은 'olidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'와 비슷합니다

. 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 다음 예제와 같이 Element 소프트웨어에 대해 NetApp Support 사이트에서 제공되는 것과 출력을 비교합니다.
+
'SUDO md5sum -b <ISO>/solidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'

. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 파일 시스템에 내용을 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 '/mnt'에서 ISO 파일을 마운트 해제합니다.
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제합니다.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 업그레이드하는 관리 노드에서 다음 명령을 실행하여 관리 노드 OS 버전을 업그레이드합니다. 업그레이드 후 Active IQ Collector 및 프록시 설정과 같은 필요한 모든 구성 파일이 스크립트에 유지됩니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
업그레이드 프로세스가 완료된 후 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다. 지속적인 모니터링을 위해서는 콘솔 액세스가 필요합니다. 업그레이드를 수행할 때 콘솔 액세스가 없는 경우 SSH 로그인을 재시도하고 15분에서 30분 후에 연결을 확인합니다. 로그인하면 SSH 배너에서 업그레이드가 성공했음을 나타내는 새 OS 버전을 확인할 수 있습니다.

. 관리 노드에서 'redeploy-mnode' 스크립트를 실행하여 이전 관리 서비스 구성 설정을 유지합니다.
+

NOTE: 이 스크립트는 설정에 따라 Active IQ Collector 서비스, 컨트롤러(vCenter) 또는 프록시의 구성을 포함하여 이전 관리 서비스 구성을 유지합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: 이전에 관리 노드에서 SSH 기능을 해제한 경우 를 수행해야 합니다 link:task_mnode_ssh_management.html["SSH를 다시 비활성화합니다"] 복구된 관리 노드에서 SSH 기능을 통해 제공됩니다 link:task_mnode_enable_remote_support_connections.html["NetApp RST(Remote Support Tunnel) 세션 액세스"] 는 기본적으로 관리 노드에서 사용하도록 설정됩니다.



== 관리 노드 REST API를 사용하여 인증을 재구성합니다

(1) 관리 서비스 및 (2) Element 스토리지를 순차적으로 업그레이드한 경우 기존 관리 노드를 유지할 수 있습니다. 다른 업그레이드 순서를 따르는 경우 현재 위치 관리 노드 업그레이드 절차를 참조하십시오.

.시작하기 전에
* 관리 서비스를 2.20.69 이상으로 업데이트했습니다.
* 스토리지 클러스터에서 Element 12.3 이상이 실행되고 있습니다.
* Element 스토리지를 업그레이드한 후 관리 서비스를 순차적으로 업데이트했습니다. 설명된 순서대로 업그레이드를 완료하지 않으면 이 절차를 사용하여 인증을 다시 구성할 수 없습니다.


.단계
. 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. authorize * 를 선택하고 다음을 완료합니다.
+
.. 클러스터 사용자 이름 및 암호를 입력합니다.
.. 값이 아직 채워지지 않은 경우 클라이언트 ID를 mnode-client로 입력합니다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.


. REST API UI에서 * POST/services/reconfigure-auth * 를 선택합니다.
. 체험하기 * 를 선택합니다.
. load_images * 매개 변수에 대해 'true'를 선택합니다.
. Execute * 를 선택합니다.
+
응답 본문은 재구성이 성공했음을 나타냅니다.



[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

